import {
  amcAaumQuarterlySnapshot,
  amcMasterSnapshot,
  amcQuarterlySnapshot,
  industryMonthlySnapshot,
  otherSchemesMonthlySnapshot,
} from "@/data/source";

/**
 * Status of a single visible metric on the dashboard. Every KPI / chart
 * card surfaces one of these (via the `tone` prop) so the user can tell
 * at a glance whether the number is real, demo, pending, missing, or
 * paywalled.
 *
 *   live        — sourced from a live ingest (AMFI / screener.in / …)
 *   demo        — placeholder generated by src/data/generator.ts
 *   pending     — an AMC / metric that should be sourced but isn't yet
 *   unavailable — no source exists today (e.g. unlisted AMC P&L)
 *   locked      — paid Morningstar premium KPI, never fetched
 *
 * PR #98 retired the visible "Source: …" caption text helpers below —
 * they now return empty strings so callers passing them as a KpiCard
 * `note` produce no text. The snapshot meta + ingestion logic is
 * unchanged; the source provenance still lives in the JSON snapshots
 * for internal debugging / data audits and is still surfaced via the
 * `tone` pill on each card. Each live-source helper retains its
 * docstring + reference to the snapshot so the connection is
 * discoverable for future maintainers.
 */
export type DataStatus =
  | "live"
  | "demo"
  | "pending"
  | "unavailable"
  | "locked";

// Reference exports kept so the snapshot meta lookups don't tree-shake
// out of the build — provenance helpers still resolve them so that any
// future caption logic has the timestamps available.
const _retainedSnapshotRefs = {
  amcAaum: amcAaumQuarterlySnapshot.meta.generatedAt,
  master: amcMasterSnapshot.meta.generatedAt,
  amcQuarterly: amcQuarterlySnapshot.meta.generatedAt,
  industry: industryMonthlySnapshot.meta.generatedAt,
  otherSchemes: otherSchemesMonthlySnapshot.meta.generatedAt,
};
void _retainedSnapshotRefs;

/**
 * Live AMFI MF QAAUM provenance helper.
 * Retired as visible caption (PR #98) — returns "" so callers render
 * no source line. The metric is still MF-only by construction (AMFI's
 * Fundwise AAUM disclosure excludes PMS / AIF / offshore / advisory).
 */
export function liveAaumNote(): string {
  return "";
}

/**
 * Live screener.in P&L provenance for revenue / op profit / PAT /
 * margins. The numerator semantic is **Revenue from Operations** —
 * screener's "Sales" row on the consolidated quarterly table; Other
 * Income / treasury income are NOT included. Visible caption retired
 * in PR #98.
 */
export function liveScreenerNote(): string {
  return "";
}

/**
 * Combined provenance for yield metrics (P&L numerator + MF QAAUM
 * denominator). Visible caption retired in PR #98.
 */
export function liveYieldNote(): string {
  return "";
}

/** AMFI master list (covers /amc list + AMC names). */
export function liveAmfiMasterNote(): string {
  return "";
}

/** AMFI Other Schemes monthly disclosures. */
export function liveOtherSchemesNote(): string {
  return "";
}

/**
 * Industry monthly snapshot helper. Currently the snapshot is empty
 * and the home-page series falls through to the demo generator; the
 * `tone="demo"` indicator on cards conveys that without a verbose
 * caption.
 */
export function industryMonthlyNote(): string {
  return "";
}

/** Demo / placeholder caption — retired (tone="demo" pill conveys it). */
export function demoNote(_what: string): string {
  void _what;
  return "";
}

/** Listed AMC whose P&L hasn't been ingested yet (e.g. ICICI Pru). */
export function pendingFinancialsNote(): string {
  return "Pending · listed financials not yet sourced";
}

/** Unlisted AMC — no public quarterly P&L exists. */
export function unlistedFinancialsNote(): string {
  return "Unavailable · unlisted AMC has no standalone quarterly financials";
}

/** Paid Morningstar KPI — display-only with lock badge. */
export function lockedMorningstarNote(): string {
  return "Locked · Requires Morningstar License";
}
