import {
  amcAaumQuarterlySnapshot,
  amcMasterSnapshot,
  amcQuarterlySnapshot,
  industryMonthlySnapshot,
  otherSchemesMonthlySnapshot,
} from "@/data/source";

/**
 * Status of a single visible metric on the dashboard. Every KPI / chart
 * card surfaces one of these so the user can tell at a glance whether
 * the number is real, demo, pending, missing, or paywalled.
 *
 *   live        — sourced from a live ingest (AMFI / screener.in / …)
 *   demo        — placeholder generated by src/data/generator.ts
 *   pending     — an AMC / metric that should be sourced but isn't yet
 *   unavailable — no source exists today (e.g. unlisted AMC P&L)
 *   locked      — paid Morningstar premium KPI, never fetched
 */
export type DataStatus =
  | "live"
  | "demo"
  | "pending"
  | "unavailable"
  | "locked";

const isoDate = (iso?: string): string =>
  iso ? new Date(iso).toISOString().slice(0, 10) : "";

/** Live AMFI AAUM provenance for the AAUM denominator + Average AUM card. */
export function liveAaumNote(): string {
  return `Source: AMFI AAUM · ${isoDate(amcAaumQuarterlySnapshot.meta.generatedAt)}`;
}

/** Live screener.in P&L provenance for revenue / op profit / PAT / margins. */
export function liveScreenerNote(): string {
  return `Source: screener.in · ${isoDate(amcQuarterlySnapshot.meta.generatedAt)}`;
}

/** Combined provenance for yield metrics (P&L numerator + AAUM denominator). */
export function liveYieldNote(): string {
  return `P&L: screener.in · ${isoDate(amcQuarterlySnapshot.meta.generatedAt)} · AAUM: AMFI · ${isoDate(amcAaumQuarterlySnapshot.meta.generatedAt)}`;
}

/** AMFI master list (the "amcMaster" source covers /amc list and AMC names). */
export function liveAmfiMasterNote(): string {
  return `Source: AMFI master · ${isoDate(amcMasterSnapshot.meta.generatedAt)}`;
}

/** AMFI Other Schemes monthly disclosures. */
export function liveOtherSchemesNote(): string {
  return `Source: AMFI Other Schemes · ${isoDate(otherSchemesMonthlySnapshot.meta.generatedAt)}`;
}

/**
 * Industry monthly snapshot. Currently empty — every industry monthly
 * series falls through to the demo generator. Returns demo provenance
 * until the snapshot has rows.
 */
export function industryMonthlyNote(): string {
  return industryMonthlySnapshot.rows.length > 0
    ? `Source: AMFI industry monthly · ${isoDate(industryMonthlySnapshot.meta.generatedAt)}`
    : demoNote("industry monthly not yet sourced");
}

/** Demo / placeholder caption for a metric that doesn't have a live source yet. */
export function demoNote(what: string): string {
  return `Demo · ${what}`;
}

/** Listed AMC whose P&L hasn't been ingested yet (e.g. ICICI Pru). */
export function pendingFinancialsNote(): string {
  return "Pending source · listed financials not yet sourced";
}

/** Unlisted AMC — no public quarterly P&L exists. */
export function unlistedFinancialsNote(): string {
  return "Unavailable · unlisted AMC has no standalone quarterly financials";
}

/** Paid Morningstar KPI — display-only with lock badge. */
export function lockedMorningstarNote(): string {
  return "Locked · Requires Morningstar License";
}
